### ISSUE TITLE
Bluesnooze not working - can't uninstall

### ISSUE THREAD

**Issue by chrisbates83** [odlp/bluesnooze#41]
Hi - I've been happy with what Bluesnooze does, amazed Apple doesn't provide this bit of functionality as standard tbh. 

Recently I've found it has stopped working - my MBP is now connecting to my BT headphones when I turn them on, even when the laptop is asleep. 

I've tried deleting the app to re-install (i think this worked last time the same issue happened), but i'm told 'Bluesnooze cannot be moved to the bin because it is open'. 
I can't seem to get the icon back into the top bar in order to turn it off and delete it. 

I've now re-downloaded v1.1 and opened it, and the icon does show in the top bar. 
But now I seem to have 2 versions of Bluesnooze running! 

Please help? I'm not a coder - I've tried the suggestion of putting that text into Terminal but it doesn't seem to do anything. 
thanks

**Comment by odlp** [comment]
Hello,

Sorry to hear Bluesnooze isn't working as expected and you can't uninstall it.

I think the best steps would be to stop all Bluesnooze versions you have running, delete them, then try reinstalling (as you've been trying!). The hidden icon option does make this trickier because one can't use the regular 'Quit' option from the menu (wish I hadn't added the hide icon option as requested by other users).

To get around the "Bluesnooze cannot be moved to the bin because it is open" issue you could follow these steps:

1. Open the 'Activity Monitor' app (available in Launchpad or searching in Spotlight)

<img width="336" alt="activity-monitor" src="https://github.com/odlp/bluesnooze/assets/4125410/e5da42c7-c374-42f6-b256-53d79c80a1a9">

2. Search for 'Bluesnooze' in Activity Monitor (search bar is top right)

<img width="866" alt="search-bluesnooze" src="https://github.com/odlp/bluesnooze/assets/4125410/ac4cc45c-3819-4b3c-8769-2a02feebd4cd">

4. For each result (you may have multiple) double click on the row and then click 'Quit'

<img width="671" alt="bluesnooze-quit" src="https://github.com/odlp/bluesnooze/assets/4125410/5276afee-d763-4ea6-94b9-eed6adc20a82">

Hope this helps

**Comment by chrisbates83** [comment]
Ah! Yes thank you Oli, I hadn't thought about approaching it via Activity
monitor. Worked a treat.

All sorted now and has been re-installed. Thank you very much!
——————————————————————————-
Chris Bates
